import { getStaticPageMetadata } from "@/lib/staticPageMeta";
import PrivacyPolicyClient from "./PrivacyPolicyClient";
import prisma from "@/lib/prisma";

export const revalidate = 0;

export async function generateMetadata() {
  return getStaticPageMetadata(
    "privacy-policy",
    "Privacy Policy",
    "Porcellana Nobilita's privacy policy."
  );
}

export default async function PrivacyPolicyPage() {
  let cmsData: any = null;
  try {
    const s = await prisma.settings.findUnique({ where: { id: "global" } });
    cmsData = {
      privacyHeroTitle: s?.privacyHeroTitle,
      privacyHeroTitleColor: s?.privacyHeroTitleColor,
      privacyHeroTitleFont: s?.privacyHeroTitleFont,
      privacyHeroTitleSize: s?.privacyHeroTitleSize,
      privacyHeroImage: s?.privacyHeroImage,
      privacyHeroLabel: s?.privacyHeroLabel,
      privacyHeroLabelColor: s?.privacyHeroLabelColor,
      privacyHeroLabelFont: s?.privacyHeroLabelFont,
      privacyHeroLabelSize: s?.privacyHeroLabelSize,
      privacyIntro: s?.privacyIntro,
      privacyIntroColor: s?.privacyIntroColor,
      privacyIntroFont: s?.privacyIntroFont,
      privacyIntroSize: s?.privacyIntroSize,
      privacySec1Heading: s?.privacySec1Heading,
      privacySec1HeadingColor: s?.privacySec1HeadingColor,
      privacySec1HeadingFont: s?.privacySec1HeadingFont,
      privacySec1HeadingSize: s?.privacySec1HeadingSize,
      privacySec1Item1Heading: s?.privacySec1Item1Heading,
      privacySec1Item1HeadingColor: s?.privacySec1Item1HeadingColor,
      privacySec1Item1HeadingFont: s?.privacySec1Item1HeadingFont,
      privacySec1Item1HeadingSize: s?.privacySec1Item1HeadingSize,
      privacySec1Item1Text: s?.privacySec1Item1Text,
      privacySec1Item1TextColor: s?.privacySec1Item1TextColor,
      privacySec1Item1TextFont: s?.privacySec1Item1TextFont,
      privacySec1Item1TextSize: s?.privacySec1Item1TextSize,
      privacySec1Item2Heading: s?.privacySec1Item2Heading,
      privacySec1Item2HeadingColor: s?.privacySec1Item2HeadingColor,
      privacySec1Item2HeadingFont: s?.privacySec1Item2HeadingFont,
      privacySec1Item2HeadingSize: s?.privacySec1Item2HeadingSize,
      privacySec1Item2Text: s?.privacySec1Item2Text,
      privacySec1Item2TextColor: s?.privacySec1Item2TextColor,
      privacySec1Item2TextFont: s?.privacySec1Item2TextFont,
      privacySec1Item2TextSize: s?.privacySec1Item2TextSize,
      privacySec1Item3Heading: s?.privacySec1Item3Heading,
      privacySec1Item3HeadingColor: s?.privacySec1Item3HeadingColor,
      privacySec1Item3HeadingFont: s?.privacySec1Item3HeadingFont,
      privacySec1Item3HeadingSize: s?.privacySec1Item3HeadingSize,
      privacySec1Item3Text: s?.privacySec1Item3Text,
      privacySec1Item3TextColor: s?.privacySec1Item3TextColor,
      privacySec1Item3TextFont: s?.privacySec1Item3TextFont,
      privacySec1Item3TextSize: s?.privacySec1Item3TextSize,
      privacySec2Heading: s?.privacySec2Heading,
      privacySec2HeadingColor: s?.privacySec2HeadingColor,
      privacySec2HeadingFont: s?.privacySec2HeadingFont,
      privacySec2HeadingSize: s?.privacySec2HeadingSize,
      privacySec2Intro: s?.privacySec2Intro,
      privacySec2IntroColor: s?.privacySec2IntroColor,
      privacySec2IntroFont: s?.privacySec2IntroFont,
      privacySec2IntroSize: s?.privacySec2IntroSize,
      privacySec2Item1: s?.privacySec2Item1,
      privacySec2Item1Color: s?.privacySec2Item1Color,
      privacySec2Item1Font: s?.privacySec2Item1Font,
      privacySec2Item1Size: s?.privacySec2Item1Size,
      privacySec2Item2: s?.privacySec2Item2,
      privacySec2Item2Color: s?.privacySec2Item2Color,
      privacySec2Item2Font: s?.privacySec2Item2Font,
      privacySec2Item2Size: s?.privacySec2Item2Size,
      privacySec2Item3: s?.privacySec2Item3,
      privacySec2Item3Color: s?.privacySec2Item3Color,
      privacySec2Item3Font: s?.privacySec2Item3Font,
      privacySec2Item3Size: s?.privacySec2Item3Size,
      privacySec2Item4: s?.privacySec2Item4,
      privacySec2Item4Color: s?.privacySec2Item4Color,
      privacySec2Item4Font: s?.privacySec2Item4Font,
      privacySec2Item4Size: s?.privacySec2Item4Size,
      privacySec2Item5: s?.privacySec2Item5,
      privacySec2Item5Color: s?.privacySec2Item5Color,
      privacySec2Item5Font: s?.privacySec2Item5Font,
      privacySec2Item5Size: s?.privacySec2Item5Size,
      privacySec3Heading: s?.privacySec3Heading,
      privacySec3HeadingColor: s?.privacySec3HeadingColor,
      privacySec3HeadingFont: s?.privacySec3HeadingFont,
      privacySec3HeadingSize: s?.privacySec3HeadingSize,
      privacySec3Text: s?.privacySec3Text,
      privacySec3TextColor: s?.privacySec3TextColor,
      privacySec3TextFont: s?.privacySec3TextFont,
      privacySec3TextSize: s?.privacySec3TextSize,
      privacySec4Heading: s?.privacySec4Heading,
      privacySec4HeadingColor: s?.privacySec4HeadingColor,
      privacySec4HeadingFont: s?.privacySec4HeadingFont,
      privacySec4HeadingSize: s?.privacySec4HeadingSize,
      privacySec4Text: s?.privacySec4Text,
      privacySec4TextColor: s?.privacySec4TextColor,
      privacySec4TextFont: s?.privacySec4TextFont,
      privacySec4TextSize: s?.privacySec4TextSize,
      privacySec5Heading: s?.privacySec5Heading,
      privacySec5HeadingColor: s?.privacySec5HeadingColor,
      privacySec5HeadingFont: s?.privacySec5HeadingFont,
      privacySec5HeadingSize: s?.privacySec5HeadingSize,
      privacySec5Text: s?.privacySec5Text,
      privacySec5TextColor: s?.privacySec5TextColor,
      privacySec5TextFont: s?.privacySec5TextFont,
      privacySec5TextSize: s?.privacySec5TextSize,
      privacySec6Heading: s?.privacySec6Heading,
      privacySec6HeadingColor: s?.privacySec6HeadingColor,
      privacySec6HeadingFont: s?.privacySec6HeadingFont,
      privacySec6HeadingSize: s?.privacySec6HeadingSize,
      privacySec6Text: s?.privacySec6Text,
      privacySec6TextColor: s?.privacySec6TextColor,
      privacySec6TextFont: s?.privacySec6TextFont,
      privacySec6TextSize: s?.privacySec6TextSize,
    };
  } catch (e) {
    cmsData = null;
  }
  return <PrivacyPolicyClient cmsData={cmsData} />;
}
